services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: checkfacil-api
    environment:
      # Banco de Dados
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # Auth
      - JWT_SECRET=${JWT_SECRET}
      # App
      - PORT=${PORT:-3001}
      # Evolution API
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}
    ports:
      - "3001"
    restart: unless-stopped
