version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkfacil-api
    restart: always
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checkfacil.rule=Host(`espacocriar.4growthbr.space`)"
      - "traefik.http.routers.checkfacil.entrypoints=websecure"
      - "traefik.http.routers.checkfacil.tls.certresolver=letsencrypt"
    networks:
      - web

networks:
  web:
    external: true
