version: '3'

services:
  espacocriar-api-v2:
    build: .
    container_name: espacocriar-api-v2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.espacocriar.rule=Host(`espacocriar.4growthbr.space`)"
      - "traefik.http.services.espacocriar-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.espacocriar.entrypoints=http"
    networks:
      - traefik

networks:
  traefik:
    external: true
